name: plane_pal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.6.2
  shadcn_ui: ^0.16.3
  shared_preferences: ^2.3.4
  google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_map_animations: ^0.8.0
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.16
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  intl: ^0.19.0
  flex_color_scheme: ^8.0.2
  timezone: ^0.10.0
  openapi:
    path: ../openapi
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  error_or: ^0.4.0
  toastification: ^2.3.0
  provider: ^6.1.2
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/geist.ttf
    - family: CalSans
      fonts:
        - asset: assets/fonts/calsans.ttf
          weight: 600
